baseURL = "http://chcherieho.github.io/"
languageCode = "en-us"
title = "Cherie Ho"
theme = "roxo-hugo"
summarylength = 25

# Site Menus
[menu]
# Navbar Menus
[[menu.nav]]
name = "Home"
url = ""
weight = 1
[[menu.nav]]
name = "About"
url = "about"
weight = 2
[[menu.nav]]
name = "Blog"
url = "blog"
weight = 3
[[menu.nav]]
name = "Get in touch"
url = "contact"
weight = 4

# Site Params
[params]
logo = "images/logo.png"
logo_footer = "images/logo-footer.png"
favicon_icon = "images/favicon.ico"
favicon_shortcut_icon = "images/favicon.png"
custom_stylesheets = []                      # [ "scss/my_1.scss", "scss/my_2.scss" ]
dateFormat = "26 FEB 1994"
# Meta data
description = "Cherie Ho | Bioenergetic Therapy | Toronto"
author = "Cherie Ho"
# Google Analitycs
# googleAnalitycsID = "Your ID"
# We're using formspree.io for form handling, paste your formspree url below
fabform = "https://fabform.io/f/USAg2Jl"

# Contact Form
[params.contactForm]
placeholder_first_name = "Tom"
placeholder_last_name = "Bloggins"
placeholder_email = "example@gmail.com"
placeholder_project_type = "Message Type"
placeholder_about_the_project = "Hello Cherie, I would like to book a session with you. I am available..."
send_message = "Send Message"

[[params.contactForm.projectType]]
value = "book"
title = "Bookings"
[[params.contactForm.projectType]]
value = "question"
title = "Curiousity"

# Navbar Action Button
[params.navAction]
status = true
name = "Get in touch"
url = "contact"


# Banner Section
[params.banner]
enable = true
background_image = "images/backgrounds/hero-background.jpg"
heading = "Bioenergetic Healing"
tagline = "Toronto based Practitioner"
primary_button = "Learn More"
primary_button_url = "about"
secondary_button = "Connect"
secondary_button_url = "contact"

[params.blog]
read_more = "read more"

[params.footer]
params.footer.qr_print = false
# Footer Contact Info
[params.footer.contactInfo]
title = "Contact Info"
# address = "1234 North Luke Lane, South Bend, IN 360001"
phone = "123-456-7890"
email = "info@chcherieho.github.io"
# Footer Sitemap
[params.footer.sitemap]
title = "Sitemap"
[[params.footer.sitemap.link]]
name = "About"
url = "about"
[[params.footer.sitemap.link]]
name = "Blog"
url = "blog"
[[params.footer.sitemap.link]]
name = "Contact"
url = "contact"
# Footer Social Media
[params.footer.social]
title = "Social Media"
[[params.footer.social.link]]
url = "#"
name = "Instagram"
[[params.footer.social.link]]
name = "WhatsApp"
url = "#"
# [[params.footer.social.link]]
# name = "Dribbble"
# url = "#"
# Footer Service
[params.footer.service]
title = "Services:"
description = "Bioenergetic Healing, Supplements, Nutrition, Energy Work"
[params.footer.back_to_top]
description = "Top"
